repos:

  # Isort
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.9.1
  hooks:
  - id: isort
    args: [-m3, --trailing-comma]
    exclude: settings

  # Black
- repo: https://github.com/ambv/black
  rev: 21.6b0
  hooks:
    - id: black
      language_version: python3.7
      types: [file, python]
      exclude: settings

  # Flake8
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
    - id: flake8
      language_version: python3.7
      args: [--max-line-length=100,--extend-ignore=E203]
      exclude: settings
